// <auto-generated />
namespace Ng2Net.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HtmlContentUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HtmlContentUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201611122054310_HtmlContentUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
