export * from './content/content-list/content-list.component';
export * from './content/content-edit/content-edit.component';
export * from './login/login.component';
export * from './app-header/app-header.component';
export * from './menu-aside/menu-aside.component';
export * from './reset-password/reset-password.component';
export * from './forgot-password/forgot-password.component';
export * from './home/home.component';
export * from './backend-master/backend-master.component';
